create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  source_name text,
  raw_text text,
  created_at timestamptz default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id bigint references public.plans(id) on delete cascade,
  title text not null,
  description text default '',
  date_text text default '',
  time_text text default '',
  location text default '',
  responsible text default '',
  participants text default '',
  priority text default 'NORMAL',
  status text default 'TODO',
  ai_plan jsonb,
  created_at timestamptz default now()
);

create index if not exists plans_user_id_idx on public.plans(user_id);
create index if not exists tasks_user_id_idx on public.tasks(user_id);

alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.tasks enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select using (id = auth.uid());
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert with check (id = auth.uid());
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists plans_select_own on public.plans;
create policy plans_select_own on public.plans for select using (user_id = auth.uid());
drop policy if exists plans_insert_own on public.plans;
create policy plans_insert_own on public.plans for insert with check (user_id = auth.uid());
drop policy if exists plans_update_own on public.plans;
create policy plans_update_own on public.plans for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists plans_delete_own on public.plans;
create policy plans_delete_own on public.plans for delete using (user_id = auth.uid());

drop policy if exists tasks_select_own on public.tasks;
create policy tasks_select_own on public.tasks for select using (user_id = auth.uid());
drop policy if exists tasks_insert_own on public.tasks;
create policy tasks_insert_own on public.tasks for insert with check (user_id = auth.uid());
drop policy if exists tasks_update_own on public.tasks;
create policy tasks_update_own on public.tasks for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists tasks_delete_own on public.tasks;
create policy tasks_delete_own on public.tasks for delete using (user_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, username, name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)),
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();