create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists plans (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  title text not null,
  source_name text,
  raw_text text,
  created_at timestamptz default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  plan_id bigint references plans(id) on delete cascade,
  title text not null,
  description text default '',
  date_text text default '',
  time_text text default '',
  location text default '',
  responsible text default '',
  participants text default '',
  priority text default 'NORMAL',
  status text default 'TODO',
  ai_plan jsonb,
  created_at timestamptz default now()
);

create index if not exists plans_user_id_idx on plans(user_id);
create index if not exists tasks_user_id_idx on tasks(user_id);
create index if not exists tasks_plan_id_idx on tasks(plan_id);