create table if not exists plans (
  id bigint generated by default as identity primary key,
  title text not null,
  source_name text,
  raw_text text,
  created_at timestamptz default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  plan_id bigint references plans(id) on delete cascade,
  title text not null,
  description text default '',
  date_text text default '',
  time_text text default '',
  location text default '',
  responsible text default '',
  participants text default '',
  priority text default 'NORMAL',
  status text default 'TODO',
  ai_plan jsonb,
  created_at timestamptz default now()
);

create index if not exists tasks_plan_id_idx on tasks(plan_id);